server.port=8080
spring.datasource.url=jdbc:postgresql://ep-proud-leaf-am4d7ba9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aftzv5G4jFUV
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true

